"""
teste
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="python_1")
def python_1_func():
    print('Teste')

default_args={
    "owner": "Cristiane Lopes,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2025-02-05", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Cristiane Lopes": "mailto:cristiane.lopes.assis@gmail.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/cm6s60kdl1wt401mdpn4d8w2z/cloud-ide/cm6s689hv1vvl01ivuy2rzunn/cm6s6elt11vwx01ivxmp6g2fl",
    },
)
def teste():
    python_1 = python_1_func()

dag_obj = teste()
